### ISSUE TITLE
As a user, I want to view all contact list, so that I can get detail about individual.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/lf-contact-manager#1]
**Tasks**

>  Frontend
 - [x] Create a table view that contains the following: 
 - [x] sort in the table. 
    - [x] Person Name in alphabetical order.
    - [x] Favorite ones first
 - [x] Show favorite contact at the beginning of the page. 

- [x] Add new contact button. Which enable user to add new user by taking to add new contact page. 
- [x] Keep the table at a fix width when viewing in larger screen. 

> Backend
 - [x] Check if the user is unauthorized or not. 
    - [x] If yes, return back list of all contact information. 
       - [x] If there is no contact, send empty response. 
       - [x] Filter data, according to query response, if there are any. 
 - [x] Send 403 HTTP code if the user is forbidden to access that data. 
 - [x] If favorite button is clicked, send a request to update the contact list to change isFavorite to true. by default - at false. 

> API:
- GET /contacts	 
---

**Form/Table Contains**

 - Person Name
 - Favorite button. 
- Contact detail: Home, Work, Mobile
 - Edit button: Which enable user to edit information by taking the user to edit page. 
- Delete button: Which able user to delete information. 

---

**Priority** :  Medium

---

**Estimate** :  1 days. 

---

**Acceptance criteria**

 - [x] User is able to see list of contact, he/she added. 
 - [x] User is able to toggle on the favorite button. 
 - [x] User is able to see more detail when accordance is pressed. 
 - [x] If no data present, show an illustration and suggest user to add new contact. 
 - [x] If any error generate, user show get flash notification about said error. 
 - [x] If user try to visit any page that doesnot exist. 404 error, along with a-link to go back to dashboard should be shown.

---
**Screenshot**

---
