### ISSUE TITLE
As a user, I add new contact detail, so that I can view them later.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/lf-contact-manager#2]
**Tasks**

>  Frontend
 - [x] Display form containing the following. 
 - [x] Validation check should be formed. 
    - [x]  Name - only alphabet are allowed. 
    - [x]  Phone - only number are allowed. Limited to 9 for tel and 10 for mobile no.
    - [x]  Address - limited to alpha-numeric. 
    - [x]  Email - check for valid email id. Eg: example@example.com 
    - [x] Organization - only alpha-numeric is allowed. 
 - [x] Success or Failure message should be shown after "Save" button is clicked.
 - [x] Form should reset to empty if success. If failure, the said box should be displayed in red to indicate mistake with error message. 

> Backend
 - [x] Validation check should be formed. 
    - [x]  Name - only alphabet are allowed. 
    - [x]  Phone - only number are allowed. Limited to 9 for tel and 10 for mobile no. 
    - [x]  Address - limited to alpha-numeric. 
    - [x]  Email - check for valid email id. Eg: example@example.com 
    - [x] Organization - only alpha-numeric is allowed. 
- [x] Validate data should be save to database. 
- [x] No-validate data should be sent error message, status, back to client. 

> API
- POST /contacts
---

**Form/Table Contains**

- Name
- Phone = Can have multiple phone number. 
- Photograph
- Address
- Email
- Organization

---

**Priority** :  Medium

---

**Estimate** :  1 days. 

---

**Acceptance criteria**

 - [x] User should be able to add new contact detail. 
 - [x] User should be able to know if the save was a success or not? 
 - [x] User should be able to get proper validation message according. 
 - [x] User should have access to go back to different pages. 

---
**Screenshot**

---
