### ISSUE TITLE
As a user, I want to delete existing record, so that I remove it from contact list.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/lf-contact-manager#4]
**Tasks**

>  Frontend
 - [x] In accordance, if user press "Delete" button, show modal confirming if the user really wants to delete or not with a warning stating deleted record cannot be recovered. 
 - [x] Update table to display new data after deletion.

> Backend
 - [x] Delete user according to ID send. 
 - [x] Send status accordingly.

> API
- DELETE /contacts/{contact_id}

---

**Priority** :  Medium

---

**Estimate** :  1 days. 

---

**Acceptance criteria**

 - [x] User should be able to delete contact detail.  

---
**Screenshot**

---
