### ISSUE TITLE
As a user, I want to login into the system.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/lf-contact-manager#6]
**Tasks**

>  Frontend

 - [x] Create login page. 
 - [x] Add validation. 
	 - [x] Red color - Wrong, Green color - Correct
	 - [x] Display error message to indicate what the issue is. 

> Backend

 - [x] Field validation. 
 - [x] Set error message according to validation
 - [x] Check username and password in the system. 
	 - [x] If present, response sucessfully.
	 - [x] If not present, show error
- [x] Create a token based authentication mechanism 

> API: 
- POST /signin	 
---

**Form Contains**
 -  Email.
 - Password

---

**Priority** : High 

---

**Estimate** : 3 days. 

---

**Acceptance criteria**

 - [x] Given user try to login when submitting it check if the user is present in database or not and show error if the user is not present. 
 - [x] Given goes to dashboard when it logs into the system it should check for email verification, if not warning should show telling user to verify it. 

---

**Screenshot**

---
