### ISSUE TITLE
As a user, I want to reset password so that I can recover my account.

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/lf-contact-manager#7]
**Tasks**

>  Frontend

 - [ ] Create Forgot Password, Verification Code, Reset password page. 
 - [ ] Add validation. 
	 - [ ] Red color - Wrong, Green color - Correct
	 - [ ] Display error message to indicate what the issue is. 
 - [ ] Add show/hide password functionality.
 - [ ] In verification code page, the keyboard should be number pad of instead of normal. 

> Backend

 - [ ] Field validation. 
 - [ ] Set error message according to validation.
 - [ ] Send verification code to the email. 
 - [ ] Check inputted code, with the code store in database. 
 - [ ] Add resend code button. 
 - [ ] Check email. 
	 - [ ] Reset password with the new one. [store in hash]

> API
- GET /reset
- POST /verify
- POST /set-password	 
---

**Form Contains**
 -  Verification Code Page.
	 - Email. 
 - Verification Code Page. 
	 - 6 digit number input field. 
 - Reset Password Page
	 - New password
	 - Confirm password

---

**Priority** : High 

---

**Estimate** : 3 days. 

---

**Acceptance criteria**

 - [ ] Given I don't remember my password when login then it should ask user to reset password. 
 - [ ] Given I receive code when I submit the forget password form, then email should be sent with the code to be verified. 

---
