### ISSUE TITLE
Initial Project Setup : React and Node (Express) js 

### ISSUE THREAD

**Issue by sarweshmaharjan** [sarweshmaharjan/lf-contact-manager#8]
**Tasks**

- [x] Install React js - FE 
- [x] Install Node js - BE 
- [x] Include Required package as necessary. 
- [x] Setup database. 
- [x] Testing
	 
---

**Priority** :  High

---

**Estimate** :  1 days. 

---
